spotify/github-java-client

src/main/java/com/spotify/github/v3/activity/events/PullRequestReviewEvent.java
src/main/java/com/spotify/github/v3/activity/events/ReviewState.java
src/main/java/com/spotify/github/v3/clients/GitHubClient.java
src/main/java/com/spotify/github/v3/clients/PullRequestClient.java
src/main/java/com/spotify/github/v3/prs/Review.java
src/test/java/com/spotify/github/v3/activity/events/PullRequestReviewEventTest.java
src/test/java/com/spotify/github/v3/prs/ReviewTest.java

the usage of this is inconsistency in github api

Make ReviewState a String

---

src/main/java/com/spotify/github/v3/clients/RepositoryClient.java
src/test/java/com/spotify/github/v3/clients/GitHubClientTest.java
src/test/java/com/spotify/github/v3/clients/RepositoryClientTest.java
src/test/resources/com/spotify/github/v3/repos/merge_commit_item.json

API docs: https://developer.github.com/enterprise/2.18/v3/repos/merging/

Support repo merging API

---

src/main/java/com/spotify/github/v3/clients/GitDataClient.java
src/main/java/com/spotify/github/v3/clients/GitHubClient.java
src/test/java/com/spotify/github/v3/clients/GitDataClientTest.java
src/test/resources/com/spotify/github/v3/clients/reference_list.json

https://developer.github.com/v3/git/refs/#list-matching-references

Add functionality to list matching references

---

src/main/java/com/spotify/github/v3/clients/GitDataClient.java

Also add deleteBranch and deleteTags for symmetry (deleteBranch has the functionality of the old delete function)
https://developer.github.com/v3/git/refs/#delete-a-reference

Fix reference delete functionality

---

src/main/java/com/spotify/github/v3/clients/GitDataClient.java
src/test/java/com/spotify/github/v3/clients/GitDataClientTest.java
src/test/resources/com/spotify/github/v3/clients/reference.json

https://developer.github.com/v3/git/refs/#create-a-reference

Add create plain reference functionality

---

src/main/java/com/spotify/github/v3/clients/GitDataClient.java
src/test/java/com/spotify/github/v3/clients/GitDataClientTest.java
src/test/resources/com/spotify/github/v3/clients/tags_list.json

https://developer.github.com/enterprise/2.18/v3/git/refs/#list-references

Add the old list reference methods

---

src/main/java/com/spotify/github/v3/clients/PullRequestClient.java
src/main/java/com/spotify/github/v3/prs/ReviewParameters.java

It is not complete, it is missing the possibility of adding comments to
objects.

Add createReview action to PullRequestClient

---

src/main/java/com/spotify/github/v3/Team.java
src/main/java/com/spotify/github/v3/clients/GitHubClient.java
src/main/java/com/spotify/github/v3/clients/PullRequestClient.java
src/main/java/com/spotify/github/v3/prs/PullRequestItem.java
src/main/java/com/spotify/github/v3/prs/RequestReviewParameters.java
src/main/java/com/spotify/github/v3/prs/ReviewRequests.java
src/test/java/com/spotify/github/v3/TeamTest.java
src/test/java/com/spotify/github/v3/clients/PullRequestClientTest.java
src/test/java/com/spotify/github/v3/prs/RequestReviewParametersTest.java
src/test/java/com/spotify/github/v3/prs/ReviewRequestsTest.java
src/test/resources/com/spotify/github/v3/clients/requestedReviews.json
src/test/resources/com/spotify/github/v3/prs/required_reviews.json
src/test/resources/com/spotify/github/v3/team.json

Extend PullRequestClient with methods for listing, creating and removing requested reviews.
Can reach out using viktorg@spotify.com

Add Request Review functions (list, create, remove)

---

README.md

README.md: Changed GithubClient to GitHubClient

---

src/main/java/com/spotify/github/v3/prs/requests/PullRequestCreate.java
src/test/java/com/spotify/github/v3/prs/requests/PullRequestCreateTest.java

Parameter from https://docs.github.com/en/rest/reference/pulls#create-a-pull-request--parameters

Make it possible to create draft PRs

---

src/main/java/com/spotify/github/v3/clients/GitDataClient.java
src/test/java/com/spotify/github/v3/clients/GitDataClientTest.java
src/test/resources/com/spotify/github/v3/clients/recursive-tree.json

This adds the API method for fetching a tree recursively as described in the Github API reference: https://docs.github.com/en/rest/reference/git#get-a-tree

Add api method for getting recursive tree

---

pom.xml

Revert v0.1.42 & v0.1.43 release related changes

---

pom.xml

see https://maven.apache.org/guides/mini/guide-reproducible-builds.html

configure for Reproducible Builds

---

.sdkmanrc

This PR updates the java sdk version in the sdkmanrc file
The version in the file is no longer available to install.
When auto-env is enabled, the correct sdk should be installed.

feat: update java sdk version

---

.github/workflows/release.yml

feat: update setup-java action version

feat: update setup-java action version

---

pom.xml

fix: version number

---

pom.xml

feat: fix version

---

.github/workflows/release.yml

The old key might be outdated/expired

fix: Fix deployment

---

pom.xml

fix: Fix v0.3.8 release

---

.github/workflows/release.yml
pom.xml

Enables debug logging in mvn deploy task and increases its timeout to 10 minutes

chore: Enable debug logs and increased timeout for deployment

---

.github/workflows/gen-java-docs.yml
pom.xml

Generates java docs and publishes on GH Pages
Published draft - https://spotify.github.io/github-java-client/

feat: Generate javadocs and publish on GH Pages

---

src/main/java/com/spotify/github/v3/comment/Comment.java
src/test/java/com/spotify/github/v3/activity/events/IssueCommentEventTest.java
src/test/resources/com/spotify/github/v3/activity/events/fixtures/issue_comment_event.json

Noticed it's present in a lot of models but not this one! Needed for some stuff I'm working on :)

add missing nodeId to Comment

---

src/main/java/com/spotify/github/v3/prs/Comment.java
src/main/java/com/spotify/github/v3/prs/PullRequestItem.java
src/test/java/com/spotify/github/v3/activity/events/PullRequestReviewCommentEventTest.java
src/test/resources/com/spotify/github/v3/activity/events/fixtures/pull_request_review_comment_event.json

Same as #234 but for [`pull_request_review_comment`](https://docs.github.com/en/enterprise-server@3.15/webhooks/webhook-events-and-payloads#pull_request_review_comment) :)

parse nodeId to PullRequestItem
