src/main/java/com/spotify/github/v3/repos/RepositoryBase.java
URIs are not enforced by github for this field, so it breaks the deserializer if it's not valid.
=> switched the homepage to be a String

src/main/java/com/spotify/github/v3/clients/GitDataClient.java
:ref shouldn't include refs/ unless it is a create reference (or github is returning it https://developer.github.com/v3/git/refs/). Now the library will handle both cases
Allow branch + tag delete to either use fully specified names or only the usual name
=> Fix the delete reference endpoint

pom.xml
in particular this fixes the license plugin causing formatting
conflicts with maven-fmt-plugin (or the IntelliJ plugin for Google's
code style)
=> update to latest com.spotify:foss-root

pom.xml, src/main/java/com/spotify/github/v3/clients/GitHubClient.java, src/test/java/com/spotify/github/v3/clients/GitHubAuthTest.java
I noticed that the test `assertJwtEndpointWithNoKeyThrows()` was taking
10 seconds to run so I took a look into why that was.
The test method has `@Test(expected=Exception.class)` but the exception
that is thrown is different than the one that the test is expected - the
test was throwing a SocketTimeoutException after 10 seconds (which is
the OkHttpClient's default read timeout setting) because there was no
mock requests enqueued in the mock web server.
I refactored these tests to use `assertThrows` instead to assert against
the details of the thrown Exceptions, and also fixed what seems like a
bug in the `getAuthorizationHeader` method - if the client has an
accessToken, it will be used as the header, even if the request path is
one that needs a private-key-signed JWT token.
=> fix tests that fail for the wrong reasons

src/main/java/com/spotify/github/v3/clients/GitHubClient.java
body should be closed
ref: https://github.com/square/okhttp/issues/2311
Currently warnings are generated from okhttp:
```
com.spotify.githubclient.shade.okhttp3.internal.platform.Platform log
WARNING: A connection to https://ghe.spotify.net/ was leaked. Did you forget to close a response body?
To see where this was allocated, set the OkHttpClient logger level to FINE: Logger.getLogger(OkHttpClient.class.getName()).setLevel(Level.FINE);
```
=> fix warnings generated because of connection leak

README.md
The example code snippet misses the access token.
=> Pass in access token in example code

src/main/java/com/spotify/github/v3/clients/GithubPage.java
In case there is a body, it should either be read through or closed.
=> Close response to avoid leaking

src/main/java/com/spotify/github/v3/clients/GitHubClient.java
This fixes several warnings of this form (#65):
A connection to https://github.com/ was leaked. Did you forget to close a response body?
According to the okhttp documentation:
"Response bodies must be closed and may be consumed only once"
https://square.github.io/okhttp/4.x/okhttp/okhttp3/-response/body/
=> Close all ignored response bodies

README.md
Changed to https://api.github.com/.
Also cleaned up proper camel-casing of GitHub, because OCD.
=> Fixed outdated GitHub API URL

src/main/java/com/spotify/github/v3/clients/GitHubClient.java, src/main/java/com/spotify/github/v3/clients/JwtTokenIssuer.java
This is to enable the option to create the `GitHubClient` with privateKey as a `byte[]` rather than the limited option of `File` object.
use case example: privateKey file is packed in the jar file of the consuming application. creating a `File` object in that case is tedious, and would have been preferred to simply load the resources, stream it and get the bytes.
`GitHubClient` create methods expecting `File` **remain** for backwards compatibility
Would be happy to have that pushed in, or get comments about the implementation and use case
=> GitHub Client - Provide privateKey as byte array

src/main/java/com/spotify/github/v3/exceptions/RequestNotOkException.java
Before this change, if you got a `RequestNotOkException` in a log file, it wasn't possible to see which request it was that failed.
With this change in place, the path and status code of the exception are prepended to the exception message, and any logged exceptions will contain information on what operation it was that failed.
=> Add path and status code to exception message

src/main/java/com/spotify/github/v3/repos/Branch.java, src/main/java/com/spotify/github/v3/repos/BranchDeserializer.java, src/test/java/com/spotify/github/v3/clients/RepositoryClientTest.java, src/test/resources/com/spotify/github/v3/repos/branch-escape-chars-url-variation-two.json, src/test/resources/com/spotify/github/v3/repos/branch-escape-chars.json, src/test/resources/com/spotify/github/v3/repos/branch-not-protected.json
If a branch has a percent symbol in it, github will sometimes return a
URI that java's URI object can't parse. This patch ensures that in such
a case we url-escape the branch name.
=> Parse and fix broken github api urls

src/main/java/com/spotify/github/v3/repos/RepositoryBase.java, src/test/java/com/spotify/github/v3/clients/RepositoryClientTest.java, src/test/java/com/spotify/github/v3/repos/RepositoryTest.java, src/test/resources/com/spotify/github/v3/repos/repository.json, src/test/resources/com/spotify/github/v3/repos/repository_get.json
The archived property included and exposed via isArchived method.
This helps avoiding to make any github calls which would result in error when the repository is archived.
So before making such calls (create comment/status etc.) - the isArchived method could be checked to avoid making other calls.
=> Add isArchived method handling archived property of Repository

src/main/java/com/spotify/github/v3/repos/Branch.java, src/main/java/com/spotify/github/v3/repos/BranchProtectionUrlDeserializer.java, src/test/java/com/spotify/github/v3/clients/RepositoryClientTest.java, src/test/resources/com/spotify/github/v3/repos/branch-no-protection-fields.json
In https://github.com/spotify/github-java-client/pull/82 we
added a custom deserializer for the `Branch` class.
This deserializer didn't handle certain cases properly that the GH API
would return. In particular the case where the `protected` field was set
and no `protection_url` is present would lead to a NPE in the
deserializer.
To avoid this error and make the whole parser more resilient to
different API results, let's reduce the scope of the custom deserializer
to only parse the `protection_url` field instead of the whole `Branch`
class.
There should be no change in runtime behavior apart from fixing the
error cases.
=> Fix parsing non-protected branches + simplify deserialization

src/main/java/com/spotify/github/opencensus/OpenCensusSpan.java, src/main/java/com/spotify/github/v3/exceptions/RequestNotOkException.java, src/test/java/com/spotify/github/v3/clients/GitHubClientTest.java
Exposing the original response payload from github makes it easier for a client to determine the cause of problem.
=> Expose github error message in RequestNotOkException.

.github/workflows/pullrequest.yml, .github/workflows/release.yml
v1 no longer works properly, so let's upgrade
See https://github.com/codecov/codecov-action#%EF%B8%8F--deprecation-of-v1
=> Upgrade to codecov-action v2

.github/workflows/release.yml
We need to enable the `coverage` profile in the main build/publish maven
step, otherwise codecov has nothing to upload.
=> Fix coverage upload on main builds

pom.xml
See https://github.com/FasterXML/jackson-databind/issues/3428
for why the BOM version has a date suffix.
=> Upgrade jackson to 2.13.x and use their BOM

src/main/java/com/spotify/github/v3/clients/RepositoryClient.java, src/main/java/com/spotify/github/v3/exceptions/ReadOnlyRepositoryException.java, src/main/java/com/spotify/github/v3/exceptions/RequestNotOkException.java
Nesting these doesn't make much sense.
Let's remove the exception code and refactor the only usage to just
re-throw the already existing exception.
=> Remove code for nested RequestNotOkException

src/main/java/com/spotify/github/v3/clients/GitHubClient.java, src/main/java/com/spotify/github/v3/clients/RepositoryClient.java, src/main/java/com/spotify/github/v3/exceptions/ReadOnlyRepositoryException.java, src/main/java/com/spotify/github/v3/exceptions/RequestNotOkException.java, src/test/java/com/spotify/github/opencensus/OpenCensusSpanTest.java, src/test/java/com/spotify/github/v3/clients/GitHubClientTest.java
Adding the HTTP method to the failure exception allows for better
visibility into which call exactly failed. We already had the HTTP path
in the exception but there are usually multiple HTTP methods that are
valid for a single path.
=> Add HTTP method to RequestNotOkException

src/main/java/com/spotify/github/v3/clients/RepositoryClient.java, src/test/java/com/spotify/github/v3/clients/RepositoryClientTest.java
See https://docs.github.com/en/enterprise-server@3.2/rest/commits/commits#list-pull-requests-associated-with-a-commit
=> Add RepositoryClient.listPullRequestsForCommit

src/main/java/com/spotify/github/v3/clients/GitHubClient.java
Instead of hardcoding POST, let's use the original method when following
redirects. This fixes deleting commit comments (and other calls
potentially).
We'll add tests for this in a follow-up since it requires a non-trivial
amount of setup to test properly and we need to ship this fix ASAP.
Sorry.
=> Use correct HTTP method for redirects

src/main/java/com/spotify/github/v3/search/requests/SearchParameters.java, src/test/java/com/spotify/github/v3/search/requests/SearchParametersTest.java
Hello,
Added **page** and **per_page** params
according to https://docs.github.com/en/enterprise-server@3.4/rest/search#search-repositories specification, **page** and **per_page** search params are supported
=> added "page" and "per_page" search parameters

src/main/java/com/spotify/github/v3/clients/RepositoryClient.java, src/main/java/com/spotify/github/v3/repos/RepositoryPermission.java, src/test/java/com/spotify/github/v3/clients/RepositoryClientTest.java
Follow-on to #97; we did not handle 204 responses from GitHub, nor accept the permission level for the added collaborator.
=> Add repository collaborator; handle 204 response, accept permission

src/main/java/com/spotify/github/v3/checks/Annotation.java, src/main/java/com/spotify/github/v3/checks/CheckRunAction.java, src/test/java/com/spotify/github/v3/checks/AnnotationTest.java, src/test/java/com/spotify/github/v3/checks/CheckRunActionTest.java
Automatically validates the maximum length of properties.
GitHub does not validate these properly on their side (at least in GHE 3.2)
and returns 5xx HTTP responses instead. To avoid that, let's validate the data
in this client library.
The values are taken from the official GitHub documentation.
Other fields might also have restrictions that are undocumented.
We might add validation for these later.
=> Validate field lengths in checks annotations + actions

src/main/java/com/spotify/github/v3/checks/Annotation.java, src/test/java/com/spotify/github/v3/checks/AnnotationTest.java
Having JsonInclude:NON_EMPTY removes empty fields (e.g., "")
When the required fields are removed, API calls fail due to missing
fields in the request.
Let's use less restrictive JsonInclude:NON_ABSENT annotation, which
removes only null & absent fields. Required fields are anyway non-nullable.
The failing test commit https://github.com/spotify/github-java-client/pull/110/commits/5a1724f56436f8c3aff156e13205615426601585 shows how NON_EMPTY rule works
```junit
Failed tests: 
AnnotationTest.serializesWithEmptyFields:80 
Expected: is "{\"path\":\"\",\"annotation_level\":\"notice\",\"message\":\"\",\"title\":\"\",\"start_line\":1,\"end_line\":2}"
but: was "{\"annotation_level\":\"notice\",\"title\":\"\",\"start_line\":1,\"end_line\":2}"
```
^ from [failed build …
=> Serialize Annotation object with all required fields even empty

src/main/java/com/spotify/github/v3/checks/CheckRunResponse.java, src/main/java/com/spotify/github/v3/clients/ChecksClient.java, src/test/java/com/spotify/github/v3/clients/ChecksClientTest.java, src/test/resources/com/spotify/github/v3/checks/checks-run-completed-long-id-response.json
CheckRunResponse id updated to support long. We also could consider using String type in case, for example, they migrate for UUID, but in their [documentation](https://docs.github.com/en/rest/checks/runs#get-a-check-run), they handle yet as an integer which seems not to be more the case once we have numbers bigger than the supporter by int type.
Fix issue https://github.com/spotify/github-java-client/issues/103
=> Fix bug #103 type for CheckRunResponse to support long id

src/main/java/com/spotify/github/v3/checks/CheckRunOutput.java, src/test/java/com/spotify/github/v3/checks/CheckRunOutputTest.java
Automatically validates the maximum length of check run `output` properties.
GitHub does not validate these properly on their side (at least in GHE 3.2)
and returns 422 HTTP responses instead. To avoid that, let's validate the data
in this client library.
The values are taken from the [official GitHub documentation](https://docs.github.com/en/enterprise-server@3.5/rest/checks/runs#create-a-check-run)
=> Validate check run output text and summary length

src/main/java/com/spotify/github/v3/clients/ChecksClient.java, src/test/java/com/spotify/github/v3/clients/GitHubAuthTest.java
Check ID type is changed from `int` to `long` in [this PR](https://github.com/spotify/github-java-client/pull/114) 
This PR changes the method parameter for `updateCheckRun` from `int` to `long` to follow the changes and avoid lossy conversions in method invocations.
=> Update check ID type

src/main/java/com/spotify/github/v3/clients/GitHubClient.java
We had some issues with temporary 401s. Refreshing the token a bit earlier now and will monitor if it fixes the issue.
=> increased EXPIRY_MARGIN_IN_MINUTES in GitHubClient from 3 to 5 mins

src/main/java/com/spotify/github/v3/clients/GitHubClient.java, src/test/java/com/spotify/github/v3/clients/GitHubAuthTest.java
The previous behavior was resulting in the library using an expired token for a few minutes (for as long as EXPIRY_MARGIN_IN_MINUTES to be precise), and that is because we had the following timeline:
- now-5min  = 2022-12-23T09:57:00Z
- now       = 2022-12-23T10:02:00Z
- expiresAt = 2022-12-23T10:05:00Z
- now+5min  = 2022-12-23T10:07:00Z
So checking if expiresAt is before now-5min returns true until now = 2022-12-23T10:09:59Z, which means the calls will fail without the token being refreshed until that point.
=> Fix refresh token behavior on EXPIRY_MARGIN

src/main/java/com/spotify/github/v3/checks/Annotation.java, src/test/java/com/spotify/github/v3/checks/AnnotationTest.java
When start_line and end_line have different values & start_column or end_column has value, then Github API throws the following error while creating or updating a Check-run
`HTTP 422: {"resource":"CheckRun","code":"invalid","field":"annotations"}`
=> Omit start_column, end_column for multi-line annotation

README.md
Adds detailed instructions on how to release changes in the github-java-client
=> docs: add release instructions to readme

src/main/java/com/spotify/github/v3/clients/GitHubClient.java, src/main/java/com/spotify/github/v3/clients/PullRequestClient.java, src/test/java/com/spotify/github/v3/clients/PullRequestClientTest.java, src/test/resources/com/spotify/github/v3/clients/patch.txt
This also adds a new request method that accepts extra headers and doesn't try to parse JSON
=> Adding support for getting a PR's patch.

src/main/java/com/spotify/github/v3/clients/OrganisationClient.java, src/test/java/com/spotify/github/v3/clients/OrganisationClientTest.java
Updates functionality to remove parameters incorrectly passed to create teams client. These parameters are instead retrieved from the parent client (Organisation Client).
The tests have been updated to reflect these changes
=> fix: update parameters passed to create teams client

src/main/java/com/spotify/github/v3/clients/GithubAppClient.java, src/main/java/com/spotify/github/v3/clients/OrganisationClient.java, src/test/java/com/spotify/github/v3/clients/GithubAppClientTest.java, src/test/java/com/spotify/github/v3/clients/OrganisationClientTest.java, src/test/resources/com/spotify/github/v3/githubapp/installation.json
Adds the ability to instantiate the GitHubAppClient from the OrganisationClient
Updates the getInstallation() function to support getting the installations at an organisation level
Unit tests have been updated to reflect these changes
=> feat: add organisation app installation functionality 

.sdkmanrc, src/main/java/com/spotify/github/v3/orgs/requests/TeamCreate.java, src/main/java/com/spotify/github/v3/orgs/requests/TeamUpdate.java, src/test/java/com/spotify/github/v3/clients/TeamClientTest.java
Fix nil values error in create team method
=> fix: Fix nil values and int warning for parent team

src/main/java/com/spotify/github/v3/clients/PullRequestClient.java, src/test/java/com/spotify/github/v3/clients/PullRequestClientTest.java, src/test/resources/com/spotify/github/v3/clients/diff.txt
Currently there is no support for getting the diff for a pullrequest. This is done by [passing a certain header](https://docs.github.com/en/rest/overview/media-types?apiVersion=2022-11-28#diff-media-type-for-commits-commit-comparison-and-pull-requests) (`application/vnd.github.diff`) which is done in this PR
=> feat: add diff method PullRequestClient

src/main/java/com/spotify/github/v3/clients/OrganisationClient.java, src/main/java/com/spotify/github/v3/orgs/OrgMembership.java, src/main/java/com/spotify/github/v3/orgs/requests/OrgMembershipCreate.java, src/test/java/com/spotify/github/v3/clients/OrganisationClientTest.java, src/test/resources/com/spotify/github/v3/clients/org_membership.json
Exposes the ability to PUT and GET organisation members
Unit tests have been updated to reflect these changes
=> feat: add get and update endpoints for org members

.github/workflows/pullrequest.yml, .github/workflows/release.yml
This PR is meant to upgrade the different GH Actions workflows to use new versions of existing actions and use new functionalities of these actions.
Changes other than formatting:
* Update `actions/checkout` to version `4`
* Update `actions/setup-java` to version `3`
* Use cache for Maven
* User Amazon Corretto JDK distribution
* Ignore being triggered by changes in `.gitignore` and `*.md` files
* Remove usage of already archived `samuelmeuli/action-maven-publish@v1`
* Perform same action as `samuelmeuli/action-maven-publish@v1` by adding necessary release credentials to `actions/setup-java@v3` and calling `mvn deploy` manually
I tested the changed workflow triggered by `pull_request` locally. Due to the needed secrets for the `push` workflow, I could not test the releasing properly.
=> chore: update GH Actions workflows

.github/workflows/pullrequest.yml, README.md
This PR builds on top of the two previous PRs #156 and #157. After merging these two PRs, the branch of this PR should be rebased on top of `master`.
As the involved version upgrades enable the compatibility with newer Java versions, the tests should then succeed in the three different Java versions `11`, `17` and `21`.
After merging this PR, we can upgrade the version of the library to `0.2.0`.
=> chore: ensure compatibility with Java versions 17 and 21

src/main/java/com/spotify/github/v3/clients/GitHubClient.java, src/test/java/com/spotify/github/v3/clients/GitHubClientTest.java
[What]
Add non static alternative to GitHubClient scopeForInstallationId
[Why]
It makes it easier to mock github client within your project that is using github client
=> Add non static alternative to GitHubClient scopeForInstallationId

CONTRIBUTING.md
Adds a CONTRIBUTING.md guide to the github-java-client so we can better inform internal and external users on how to contribute to this library.
=> docs: add contributing guide to library

CONTRIBUTING.md, README.md
Adds the maintainers team to the docs so external users are aware of who to reach out to for review or for any questions.
=> docs: HOTS-374 add maintainers team to docs

catalog-info.yaml
As declared in our `Open Source Project Ownership` docs, we need to declare the library ownership in the `catalog-info.yaml`. As the ownership changed to `HotSauce` and we want to be accountable, we should update this declaration.
=> chore: declare ownership according to `OS Project Ownership` docs

src/main/java/com/spotify/github/v3/clients/GithubAppClient.java, src/test/java/com/spotify/github/v3/clients/GithubAppClientTest.java
Hi, this PR adds support to get the an installation's information using the installation id. Essentially, it enables to use the `/app/installations/{installation_id}` [API endpoint](https://docs.github.com/en/rest/apps/apps?apiVersion=2022-11-28#get-an-installation-for-the-authenticated-app).
=> Add support to get Installation identified by its installation id

README.md
I Fixed some Grammar and phrases in `README.md` file.
please go through that.
=> Fixed some typos in README.md file

src/main/java/com/spotify/github/v3/clients/RepositoryClient.java, src/test/java/com/spotify/github/v3/clients/RepositoryClientTest.java
Hi, this PR adds support to download the repository content as [zip](https://docs.github.com/en/rest/repos/contents?apiVersion=2022-11-28#download-a-repository-archive-zip) or [tar](https://docs.github.com/en/rest/repos/contents?apiVersion=2022-11-28#download-a-repository-archive-tar) archive.
I extended the Repository client with two separate methods to download the tar or zip archive. The methods return an Optional InputStream that can be consumed accordingly, e.g., by a `BufferedInputStream` that writes it read bytes to a `FileOutputStream` or by following this [guide](https://www.baeldung.com/convert-input-stream-to-a-file).
=> Support to download repository content (zip/tar)

README.md
Summary
=======
This PR fixes the worklow badges link and add links to our maven central page both from the badge and in the text.
=> fix(README): fix badges

.github/workflows/maven-version-determiner.py, .github/workflows/prepare-release.yml, README.md
With this PR, we step closer towards automating our release. I introduce the workflow `prepare-release`, which automates the steps which had to be performed locally before. 
The workflow can be triggered as a `workflow_dispatch` together with selecting whether it is a `PATCH`, `MINOR` or `MAJOR` release. When triggered, it computes the necessary versions via the `maven-version-determiner.py` and calls `mvn release:prepare` with these versions.
As the Maven release plugin pushes commits during its `prepare` step, the action also tries to push to GitHub. To enable these pushes via the SSH connection, I use the foreign Action `webfactory/ssh-agent`. For this action, I generated an SSH keypair which I set as a deploy key and a secret.
The idea is that the workflow `release` picks up the new …
=> cd: create GH Actions workflow to prepare release on dispatch

.github/workflows/pullrequest.yml, .github/workflows/release.yml
As the Node version used by `codecov-action@v2` is deprecated, we need to update the action to `v3`.
=> ci: update `codecov-action` to v3

.github/workflows/release-on-github.yml, .github/workflows/release.yml
The action `github-release` triggers a release on GitHub. Usually, such a release should happen when a new tag is created. As the release notes should be generated automatically and the proper notes are only available after running Maven deploy, the GitHub release gets triggered only when the workflow `maven-release` is finished.
=> cd: create workflow to trigger release on GitHub

.github/workflows/release-on-github.yml
The GitHub release did not get triggered. To work around issues like this, we should enable triggering the GitHub release manually through the web UI.
=> cd: allow manual release on GitHub through workflow

src/main/java/com/spotify/github/v3/clients/GitHubClient.java, src/main/java/com/spotify/github/v3/clients/UserClient.java, src/main/java/com/spotify/github/v3/user/requests/SuspensionReason.java, src/test/java/com/spotify/github/v3/clients/UserClientTest.java
What:
Adds a user client to allow for suspending/unsuspending users.
=> Add user client to allow for suspending/unsuspending users

.github/workflows/release.yml, README.md
As the `maven-release` workflow gets only triggered by the master ref and not by the tag, I added the functionality to retrieve the tag associated with the current SHA. If a tag is available for the current SHA, I trigger a GitHub release with this tag.
=> cd: retrieve tag for current SHA and trigger GitHub release with this tag

.github/workflows/release.yml
For using `git describe` and retrieving a successful result, the Git history including the tags has to be present. The issue is that `actions/checkout` performs a shallow clone of the depth `1`, i.e. a clone without history.
In our case, we might only require the history with tags from HEAD until the currently checked-out commit. As this library's history is not the biggest and we currently do not observe performance issues, I decided to not perform a premature optimisation and just check out the whole Git history with tags.
=> fix(cd): enable tag retrieval through increasing `fetch-depth`

src/main/java/com/spotify/github/v3/clients/RepositoryClient.java, src/main/java/com/spotify/github/v3/repos/CommitWithFolderContent.java, src/main/java/com/spotify/github/v3/repos/requests/FileCreate.java, src/main/java/com/spotify/github/v3/repos/requests/FileUpdate.java, src/test/java/com/spotify/github/v3/clients/RepositoryClientTest.java, src/test/resources/com/spotify/github/v3/repos/create-content-repsonse.json, src/test/resources/com/spotify/github/v3/repos/create-content-request.json, src/test/resources/com/spotify/github/v3/repos/update-content-repsonse.json, src/test/resources/com/spotify/github/v3/repos/update-content-request.json
See https://docs.github.com/en/rest/repos/contents?apiVersion=2022-11-28#create-or-update-file-contents.
I applied the well known engineering principle of "monkey-see-monkey-do". Hopefully my grasp of how to do things in this project is not off too much. Checkstyle yelling at me was definitely helpful.
Happy to do smaller follow-ups :)
=> feat: add support for creating and updating file contents

src/main/java/com/spotify/github/v3/clients/TeamClient.java, src/test/java/com/spotify/github/v3/clients/TeamClientTest.java, src/test/resources/com/spotify/github/v3/clients/list_members_page1.json, src/test/resources/com/spotify/github/v3/clients/list_members_page2.json
Github will list up to 30 team members by default when retrieving members from a team. If there is more that 30 members we need to iterate over the paged api.
=> Add paged version of getTeamMembers

pom.xml
Some runs of the release action fail. The failures seem to occur because of the `nexus-staging-maven-plugin`. With a version which is around 5 years younger, the release action should become more reliable.
=> chore: update version of `nexus-staging-maven-plugin`

src/main/java/com/spotify/github/v3/clients/RepositoryClient.java, src/main/java/com/spotify/github/v3/repos/RepositoryBase.java, src/main/java/com/spotify/github/v3/repos/requests/RepositoryUpdate.java, src/test/java/com/spotify/github/v3/clients/RepositoryClientTest.java
Adds Update Repository endpoint support - https://docs.github.com/en/rest/repos/repos?apiVersion=2022-11-28#update-a-repository
=> feat: Add RepoUpdate endpoint

src/main/java/com/spotify/github/v3/clients/GitHubClient.java
This is needed if you want to use the installationScopedClient with graphql api method. Otherwise we get following exception "Graphql url is not set".
=> Propagate graphql url to installation scoped client

src/main/java/com/spotify/github/v3/clients/RepositoryClient.java, src/main/java/com/spotify/github/v3/repos/requests/RepositoryDispatch.java, src/test/java/com/spotify/github/v3/clients/RepositoryClientTest.java
Adding support for the `/repos/{owner}/{repo}/dispatches` endpoint that allows us to dispatch custom webhook events from repositories to trigger workflows. See more here: https://docs.github.com/en/rest/repos/repos?apiVersion=2022-11-28#create-a-repository-dispatch-event
=> Add repository_dispatch endpoint

pom.xml, src/main/java/com/spotify/github/v3/clients/GitHubClient.java, src/main/java/com/spotify/github/v3/clients/GithubAppClient.java, src/main/java/com/spotify/github/v3/clients/UserClient.java, src/test/java/com/spotify/github/v3/clients/UserClientTest.java
**What**
Add support to get a user installation for the authenticated app.
=> Add support to get a user installation for the authenticated app

src/main/java/com/spotify/github/async/Async.java, src/main/java/com/spotify/github/v3/clients/GitHubClient.java, src/test/java/com/spotify/github/v3/clients/GitHubClientTest.java
It can be tricky to know which installation ID to provide to `withScopeForInstallationId`.
Rather than duplicating the "check for an organization installation, then check for a user installation", let's instead move that to this library so it can be reused.
This is a slow operation, but caching of the result can be handled by consumers (if needed) IMO.
=> Add `asAppScopedClient()` function for convenience

src/main/java/com/spotify/github/v3/clients/ActionsClient.java, src/main/java/com/spotify/github/v3/clients/GitHubClient.java, src/main/java/com/spotify/github/v3/clients/RepositoryClient.java, src/main/java/com/spotify/github/v3/clients/WorkflowsClient.java, src/main/java/com/spotify/github/v3/workflows/WorkflowsRepositoryResponseList.java, src/main/java/com/spotify/github/v3/workflows/WorkflowsResponse.java, src/main/java/com/spotify/github/v3/workflows/WorkflowsState.java, src/test/java/com/spotify/github/v3/clients/GitHubClientTest.java, src/test/java/com/spotify/github/v3/clients/WorkflowsClientTest.java, src/test/resources/com/spotify/github/v3/workflows/workflows-get-workflow-response.json, src/test/resources/com/spotify/github/v3/workflows/workflows-list-workflows-response.json
Hi @Abhi347!
Here is a small PR which adds get and list workflows from Github Actions API: 
- List Workflows: https://docs.github.com/en/rest/actions/workflows#list-repository-workflows
- Get Workflow: https://docs.github.com/en/rest/actions/workflows#get-a-workflow
Added tests as well for code coverage
=> Add get and list workflows from github actions API

src/main/java/com/spotify/github/v3/workflows/WorkflowsResponse.java
deletedAt field in WorkflowsResponse is not required according to the schema and therefore should be marked @Nullable.
Running without this fix causes an exception when deserialising the json response from GitHub with the root cause:
```
Cannot build WorkflowsResponse, some of required attributes are not set [deletedAt]
```
=> Make WorkflowsResponse.deletedAt field nullable

src/main/java/com/spotify/github/jackson/Json.java
Fix deprecation warning by replacing SNAKE_CASE with PropertyNamingStrategies.SNAKE_CASE.
The PropertyNamingStrategy.SNAKE_CASE constant has been deprecated in favor of PropertyNamingStrategies.SNAKE_CASE.
This commit updates the code to use the current, non-deprecated naming strategy, resolving the lint warning.
=> Fix snake case

src/main/java/com/spotify/github/v3/activity/events/CreateEvent.java, src/main/java/com/spotify/github/v3/activity/events/PushEvent.java, src/main/java/com/spotify/github/v3/activity/events/StatusEvent.java, src/main/java/com/spotify/github/v3/issues/Issue.java, src/main/java/com/spotify/github/v3/prs/Review.java, src/main/java/com/spotify/github/v3/repos/RepositoryInvitation.java
This commit removes the @Nullable annotation from Optional attributes in several files.
This was causing lint warnings because the combination of @Nullable and Optional
is not recommended. The changes have been made in the following files:
- src/main/java/com/spotify/github/v3/activity/events/StatusEvent.java
- src/main/java/com/spotify/github/v3/issues/Issue.java
- src/main/java/com/spotify/github/v3/repos/RepositoryInvitation.java
- src/main/java/com/spotify/github/v3/prs/Review.java
- src/main/java/com/spotify/github/v3/activity/events/CreateEvent.java
- src/main/java/com/spotify/github/v3/activity/events/PushEvent.java
=> Fix nullable optionals

src/main/java/com/spotify/github/v3/comment/Comment.java
The  method in  was already marked as deprecated with a javadoc tag,
but it was missing the  annotation. This commit adds the missing annotation to
resolve a lint warning.
=> Fix deprecated annotation

src/main/java/com/spotify/github/v3/issues/Label.java, src/main/java/com/spotify/github/v3/prs/PullRequest.java, src/test/java/com/spotify/github/v3/prs/PullRequestTest.java, src/test/resources/com/spotify/github/v3/prs/pull_request.json, src/test/resources/com/spotify/github/v3/search/issues.json
`PullRequest` model is missing the `labels` field. Additionally, few of the fields on the `Label` model were also missing.  
This PR fixes the issue.
=> fix: Add labels field to the PR model

pom.xml, src/main/java/com/spotify/github/jackson/CommentReactionContentDeserializer.java, src/main/java/com/spotify/github/jackson/CommentReactionContentSerializer.java, src/main/java/com/spotify/github/v3/clients/GitHubClient.java, src/main/java/com/spotify/github/v3/clients/IssueClient.java, src/main/java/com/spotify/github/v3/comment/CommentReaction.java, src/main/java/com/spotify/github/v3/comment/CommentReactionContent.java, src/test/java/com/spotify/github/v3/clients/IssueClientTest.java, src/test/java/com/spotify/github/v3/comment/CommentReactionContentTest.java
Adds the functionality to react on issue comments with emojis. This PR also includes listing and deleting those reactions for a particular comment.
=> feat: Add Issue Comment Reaction functionality

src/main/java/com/spotify/github/v3/clients/IssueClient.java
Creates overloaded methods for both int and long ids in IssueClient and marks int ids as deprecated.
=> fix: Fix the int vs long issue in IssueClient methods

src/main/java/com/spotify/github/v3/clients/GitHubClient.java, src/test/java/com/spotify/github/v3/clients/GitHubAuthTest.java
The `join()` on fetching access tokens can cause thread deadlock when there are many requests in the pool. Making the entire method chain async should fix this.
=> fix: Fix Thread deadlock because of the join() in GitHubClient

src/main/java/com/spotify/github/v3/clients/GitHubClient.java, src/main/java/com/spotify/github/v3/clients/PullRequestClient.java, src/test/java/com/spotify/github/v3/clients/PullRequestClientTest.java
Add changedFiles() method for PullRequestClient
=> feat: Add changedFiles for PR Client

src/main/java/com/spotify/github/v3/clients/GitHubClient.java, src/main/java/com/spotify/github/v3/clients/PullRequestClient.java, src/test/java/com/spotify/github/v3/clients/PullRequestClientTest.java
=> endpoint to list pr review comments

pom.xml, src/main/java/com/spotify/github/v3/clients/GithubPage.java, src/main/java/com/spotify/github/v3/clients/PullRequestClient.java, src/main/java/com/spotify/github/v3/clients/TeamClient.java, src/test/java/com/spotify/github/v3/clients/GitHubPageTest.java, src/test/java/com/spotify/github/v3/clients/IssueClientTest.java, src/test/java/com/spotify/github/v3/clients/PullRequestClientTest.java, src/test/java/com/spotify/github/v3/clients/RepositoryClientTest.java, src/test/java/com/spotify/github/v3/clients/TeamClientTest.java, src/test/resources/com/spotify/github/v3/clients/pull_request_commits_page1.json, src/test/resources/com/spotify/github/v3/clients/pull_request_commits_page2.json, src/test/resources/com/spotify/github/v3/clients/pull_request_commits_page3.json
Summary
=======
This pull request adds full support for pagination when listing commits for a given Pull Request
WORK IN PROGRESS
=> feat(pull-request): support pagination in list commits

src/main/java/com/spotify/github/v3/clients/PullRequestClient.java, src/test/java/com/spotify/github/v3/clients/PullRequestClientTest.java
adding REST endpoint for retrieving review comments
=> feat: list review comments
